name: ci
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      NGX_VER: '1.26.2'
      APL_VER: '3.21'
      HUB_ID: 'vndroid'
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "alpine-slim"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/alpine-slim
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HUB_ID }}/nginx:${{ env.NGX_VER }}-alpine${{ env.APL_VER }}-slim
      - name: Build and Push "alpine"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/alpine
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HUB_ID }}/nginx:${{ env.NGX_VER }}-alpine${{ env.APL_VER }},${{ env.REGISTRY }}/${{ env.HUB_ID }}/nginx:latest
      - name: Build and Push "alpine-perl"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/alpine-perl
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HUB_ID }}/nginx:${{ env.NGX_VER }}-alpine${{ env.APL_VER }}-perl
      - name: Build and Push "alpine-otel"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./stable/alpine-otel
          push: true
          tags: ghcr.io/${{ env.HUB_ID }}/nginx:${{ env.NGX_VER }}-alpine${{ env.APL_VER }}-otel